$lines = Get-Content lib\screens\login_screen.dart
$lines[79] = "  Widget _buildMobile(BuildContext context) {"
$newMethods = @(
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    final width = MediaQuery.of(context).size.width;",
    "    if (width >= 900) {",
    "      return _buildWeb(context);",
    "    }",
    "    return _buildMobile(context);",
    "  }",
    "",
    "  Widget _buildWeb(BuildContext context) {",
    "    return Scaffold(",
    "      backgroundColor: Colors.white,",
    "      body: Row(",
    "        children: [",
    "          Expanded(",
    "            flex: 6,",
    "            child: Container(",
    "              decoration: const BoxDecoration(",
    "                gradient: LinearGradient(",
    "                  begin: Alignment.topLeft,",
    "                  end: Alignment.bottomRight,",
    "                  colors: [kHeroBg, kBrandGreenDark],",
    "                ),",
    "              ),",
    "              padding: const EdgeInsets.symmetric(horizontal: 64, vertical: 48),",
    "              child: Column(",
    "                crossAxisAlignment: CrossAxisAlignment.start,",
    "                mainAxisAlignment: MainAxisAlignment.center,",
    "                children: [",
    "                  Row(",
    "                    children: [",
    "                      Container(",
    "                        padding: const EdgeInsets.all(10),",
    "                        decoration: BoxDecoration(",
    "                          color: Colors.white,",
    "                          borderRadius: BorderRadius.circular(12),",
    "                        ),",
    "                        child: const Icon(Icons.bolt, color: kBrandGreen, size: 28),",
    "                      ),",
    "                      const SizedBox(width: 14),",
    "                      Text(",
    "                        'GoFresh',",
    "                        style: GoogleFonts.poppins(",
    "                          color: Colors.white,",
    "                          fontSize: 28,",
    "                          fontWeight: FontWeight.w800,",
    "                        ),",
    "                      ),",
    "                    ],",
    "                  ),",
    "                  const SizedBox(height: 48),",
    "                  Text(",
    "                    'Groceries delivered\nin minutes.',",
    "                    style: GoogleFonts.poppins(",
    "                      color: Colors.white,",
    "                      fontSize: 44,",
    "                      fontWeight: FontWeight.w800,",
    "                      height: 1.15,",
    "                    ),",
    "                  ),",
    "                  const SizedBox(height: 20),",
    "                  Text(",
    "                    'Fresh produce, daily essentials and more, delivered to your door,\nfast and reliable.',",
    "                    style: GoogleFonts.poppins(",
    "                      color: Colors.white.withOpacity(0.85),",
    "                      fontSize: 16,",
    "                      height: 1.5,",
    "                    ),",
    "                  ),",
    "                  const SizedBox(height: 48),",
    "                  Row(",
    "                    children: [",
    "                      _webStat('10 min', 'Delivery'),",
    "                      const SizedBox(width: 40),",
    "                      _webStat('24/7', 'Support'),",
    "                      const SizedBox(width: 40),",
    "                      _webStat('100%', 'Fresh'),",
    "                    ],",
    "                  ),",
    "                ],",
    "              ),",
    "            ),",
    "          ),",
    "          Expanded(",
    "            flex: 5,",
    "            child: Center(",
    "              child: ConstrainedBox(",
    "                constraints: const BoxConstraints(maxWidth: 400),",
    "                child: Column(",
    "                  mainAxisSize: MainAxisSize.min,",
    "                  crossAxisAlignment: CrossAxisAlignment.start,",
    "                  children: [",
    "                    Text(",
    "                      'WELCOME BACK',",
    "                      style: GoogleFonts.poppins(",
    "                        color: kBrandGreen,",
    "                        fontSize: 13,",
    "                        fontWeight: FontWeight.w700,",
    "                        letterSpacing: 1.2,",
    "                      ),",
    "                    ),",
    "                    const SizedBox(height: 8),",
    "                    Text(",
    "                      'Log In or Sign Up',",
    "                      style: GoogleFonts.poppins(",
    "                        color: Colors.black87,",
    "                        fontSize: 32,",
    "                        fontWeight: FontWeight.w800,",
    "                      ),",
    "                    ),",
    "                    const SizedBox(height: 12),",
    "                    Text(",
    "                      'Enter your mobile number to continue to GoFresh.',",
    "                      style: GoogleFonts.poppins(",
    "                        color: Colors.black54,",
    "                        fontSize: 15,",
    "                      ),",
    "                    ),",
    "                    const SizedBox(height: 36),",
    "                    Text(",
    "                      'Mobile Number',",
    "                      style: GoogleFonts.poppins(",
    "                        color: Colors.black87,",
    "                        fontSize: 13,",
    "                        fontWeight: FontWeight.w600,",
    "                      ),",
    "                    ),",
    "                    const SizedBox(height: 8),",
    "                    Container(",
    "                      decoration: BoxDecoration(",
    "                        border: Border.all(color: Colors.grey.shade300),",
    "                        borderRadius: BorderRadius.circular(10),",
    "                      ),",
    "                      padding: const EdgeInsets.symmetric(horizontal: 16),",
    "                      child: Row(",
    "                        children: [",
    "                          Text('+91', style: GoogleFonts.poppins(fontSize: 15, fontWeight: FontWeight.w600)),",
    "                          const SizedBox(width: 10),",
    "                          Container(width: 1, height: 24, color: Colors.grey.shade300),",
    "                          const SizedBox(width: 12),",
    "                          Expanded(",
    "                            child: TextField(",
    "                              controller: _phoneController,",
    "                              keyboardType: TextInputType.number,",
    "                              maxLength: 10,",
    "                              inputFormatters: [FilteringTextInputFormatter.digitsOnly],",
    "                              onChanged: (_) => setState(() {}),",
    "                              decoration: const InputDecoration(",
    "                                border: InputBorder.none,",
    "                                counterText: '',",
    "                                hintText: 'Enter mobile number',",
    "                                contentPadding: EdgeInsets.symmetric(vertical: 14),",
    "                              ),",
    "                              style: GoogleFonts.poppins(fontSize: 15),",
    "                            ),",
    "                          ),",
    "                        ],",
    "                      ),",
    "                    ),",
    "                    const SizedBox(height: 24),",
    "                    SizedBox(",
    "                      width: double.infinity,",
    "                      height: 52,",
    "                      child: ElevatedButton(",
    "                        onPressed: _isValid && !_isSending ? _continue : null,",
    "                        style: ElevatedButton.styleFrom(",
    "                          backgroundColor: kBrandGreen,",
    "                          disabledBackgroundColor: Colors.grey.shade300,",
    "                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),",
    "                          elevation: 0,",
    "                        ),",
    "                        child: _isSending",
    "                            ? const SizedBox(",
    "                                width: 22,",
    "                                height: 22,",
    "                                child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2.5),",
    "                              )",
    "                            : Row(",
    "                                mainAxisAlignment: MainAxisAlignment.center,",
    "                                children: [",
    "                                  Text(",
    "                                    'Send OTP',",
    "                                    style: GoogleFonts.poppins(",
    "                                      color: Colors.white,",
    "                                      fontSize: 16,",
    "                                      fontWeight: FontWeight.w700,",
    "                                    ),",
    "                                  ),",
    "                                  const SizedBox(width: 8),",
    "                                  const Icon(Icons.arrow_forward, color: Colors.white, size: 18),",
    "                                ],",
    "                              ),",
    "                      ),",
    "                    ),",
    "                    const SizedBox(height: 24),",
    "                    Center(",
    "                      child: Text(",
    "                        'Protected access - GoFresh',",
    "                        style: GoogleFonts.poppins(color: Colors.black38, fontSize: 12),",
    "                      ),",
    "                    ),",
    "                  ],",
    "                ),",
    "              ),",
    "            ),",
    "          ),",
    "        ],",
    "      ),",
    "    );",
    "  }",
    "",
    "  Widget _webStat(String value, String label) {",
    "    return Column(",
    "      crossAxisAlignment: CrossAxisAlignment.start,",
    "      children: [",
    "        Text(",
    "          value,",
    "          style: GoogleFonts.poppins(",
    "            color: Colors.white,",
    "            fontSize: 22,",
    "            fontWeight: FontWeight.w800,",
    "          ),",
    "        ),",
    "        Text(",
    "          label,",
    "          style: GoogleFonts.poppins(",
    "            color: Colors.white.withOpacity(0.7),",
    "            fontSize: 13,",
    "          ),",
    "        ),",
    "      ],",
    "    );",
    "  }"
)
$before = $lines[0..136]
$after = $lines[137..($lines.Length - 1)]
$updated = $before + $newMethods + $after
Set-Content -Path lib\screens\login_screen.dart -Value $updated -Encoding UTF8
Write-Host "Web layout added successfully"