// Downloads the tax invoice PDF generated by the backend (server-side,
// using real seller details + a Postgres-backed invoice record) instead of
// building one locally. This keeps the customer's invoice identical to the
// one admins see in the admin panel and avoids maintaining two separate
// invoice layouts/seller configs.
import 'dart:io';
import 'dart:typed_data';
import 'package:file_saver/file_saver.dart';
import 'package:http/http.dart' as http;
import 'package:printing/printing.dart';
import 'package:open_filex/open_filex.dart';
import 'package:path_provider/path_provider.dart';
import 'package:flutter/foundation.dart';
import '../models/order_model.dart';
import '../services/api_service.dart';
import 'download_notification_service.dart';
class InvoiceGenerator {
  /// Fetches the invoice PDF bytes for [order] from the backend
  /// (GET /orders/:id/invoice/pdf). Throws if the request fails or the
  /// invoice isn't available yet (e.g. payment not confirmed).
  static Future<Uint8List> fetchInvoicePdf(Order order) async {
    final headers = await ApiService.getHeaders();
    final response = await http
        .get(
          Uri.parse('${ApiService.baseUrl}/orders/${order.id}/invoice/pdf'),
          headers: headers,
        )
        .timeout(const Duration(seconds: 30));
    if (response.statusCode != 200) {
      throw Exception('Invoice not available (status ${response.statusCode})');
    }
    return response.bodyBytes;
  }
  /// Downloads the invoice PDF straight into the device's Downloads folder
  /// via MediaStore (file_saver) - no "Save As" picker dialog. No storage
  /// permission is needed on Android 10+ since MediaStore handles the
  /// write itself under scoped storage.
  /// Returns true if the file was saved/shared successfully.
  static Future<bool> downloadInvoice({
    required Order order,
    required String customerName,
  }) async {
    final bytes = await fetchInvoicePdf(order);
    final fileName = 'Invoice_Order${order.id}_${DateTime.now().millisecondsSinceEpoch}';
    if (Platform.isAndroid || Platform.isIOS) {
      String savedPath;
      try {
        savedPath = await FileSaver.instance.saveFile(
          name: fileName,
          bytes: bytes,
          fileExtension: 'pdf',
          mimeType: MimeType.pdf,
        );
      } catch (saveError) {
        throw Exception('Save failed: $saveError');
      }
      if (savedPath.isEmpty) {
        // Save failed silently / was denied - not treated as a hard error.
        return false;
      }
      // Open the invoice immediately after saving, Zepto-style, using the
      // bytes already in memory. This avoids re-reading the file from disk
      // (which fails with EACCES under scoped storage) and gives an
      // instant native PDF preview inside the app.
      await DownloadNotificationService.showDownloadComplete(
        fileName: '$fileName.pdf',
        filePath: savedPath,
      );
      // After the notification, show the system "Open with" chooser.
      try {
        final tmp = await getTemporaryDirectory();
        final tmpFile = File('${tmp.path}/$fileName.pdf');
        await tmpFile.writeAsBytes(bytes, flush: true);
        await OpenFilex.open(tmpFile.path, type: 'application/pdf');
      } catch (e) {
        debugPrint('open invoice failed: $e');
      }
      return true;
    } else {
      await Printing.sharePdf(bytes: bytes, filename: '$fileName.pdf');
      return true;
    }
  }
}
